<h3>List Users</h3>
<a href="<?php echo $this->url('register') ?>""> + Add User</a>
<a style="float: right;" href="<?php echo $this->url('logout') ?>""> Logout?</a>
<table class="table">
 	<thead>
	    <tr>
	      <th scope="col">UserNam</th>
	      <th scope="col">Email</th>
	      <th scope="col">Option</th>
	    </tr>
  	</thead>
  	<tbody>
  		<?php foreach($users as $user): ?>
		    <tr>
		      <td><?=$this->escapeHtml($user->getUsername())?></td>
		      <td><?=$this->escapeHtml($user->getEmail())?></td>
		      <td>
		      	<a href="">Edit</a> 
         		<a href="">Delete</a> 
		      </td>
		    </tr>
		<?php endforeach; ?>
  	</tbody>
</table>