<h3>List Users</h3>
<a href="<?php echo $this->url('add') ?>""> + Add User</a>
<table class="table">
 	<thead>
	    <tr>
	      <th scope="col">UserNam</th>
	      <th scope="col">Email</th>
	      <th scope="col">Option</th>
	    </tr>
  	</thead>
  	<tbody>
  		<?php foreach($users as $user): ?>
		    <tr>
		      <td><?php echo $user->user_name; ?></td>
		      <td><?php echo $user->email; ?></td>
		      <td>
		      	<a href="">Edit</a> 
         		<a href="">Delete</a> 
		      </td>
		    </tr>
		<?php endforeach; ?>
  	</tbody>
</table>