<h3> Log In</h3>
<form>
    <div class="form-group">
        <label for="exampleInputEmail1">Email address</label>
        <input type="email" class="form-control" placeholder="Enter email">
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
    </div>
    <div class="form-group">
        <a href="<?php echo $this->url('add') ?>""> Registration</a>
    </div>
 
    <button type="submit" class="btn btn-primary">Submit</button>
</form>