<!-- Filename: module/Blog/view/blog/write/add.phtml -->
<h1>Add a blog post</h1>

<?php
$form = $this->form;
//$form->setAttribute('action', $this->url());

//$fieldset = $form->get('post');

//$title = $fieldset->get('title');
/*$title->setAttribute('class', 'form-control');
$title->setAttribute('placeholder', 'Post title');*/

//$text = $fieldset->get('text');
/*$text->setAttribute('class', 'form-control');
$text->setAttribute('placeholder', 'Post content');*/

//$submit = $form->get('submit');
//$submit->setAttribute('class', 'btn btn-primary');



echo $this->form()->openTag($form);
?>

<div class="form-group">
    <?=$this->formLabel($form->get('title'));?>
    <?php
        echo $this->formElement($form->get('title'));
        echo $this->formElementErrors($form->get('title'));
        
    ?>
</div>

<div class="form-group">
    <?=$this->formLabel($form->get('text'));?>
    <?php
        echo $this->formElement($form->get('text'));
        echo $this->formElementErrors($form->get('text'));
        
    ?>
</div>
<div class="col-md-3">
            <?php
                echo $this->formRow($form->get('submit'));
            ?>
        </div>

<?php
    echo $this->form()->closeTag(); //</form>
?>