<?=$this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Bee Shop')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('css/owl.carousel.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/animate.css'))
            ->prependStylesheet($this->basePath('css/blog.css'))
        ?>

        <!-- Scripts -->
         <?= $this->headScript()
            ->prependFile($this->basePath('js/jquery-3.2.1.min.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/owl.carousel.min.js'))
            ->prependFile($this->basePath('js/mixitup.min.js'))
            ->prependFile($this->basePath('js/sly.min.js'))
            ->prependFile($this->basePath('js/jquery.nicescroll.min.js'))
            ->prependFile($this->basePath('js/main.js'))
        ?>
        
    </head>
    <body>
       <header class="header-section" id="nav-home">
           <div class="container-fluid">
               
               <div class="site-logo">
                   <img src="/img/logo.png" alt="logo">
               </div>
          
               <div class="nav-switch">
                   <i class="fa fa-bars"></i>
               </div>
               <div class="header-right">
                   <a href="cart.html" class="card-bag"><img src="/img/icons/bag.png" alt=""><span>2</span></a>
                   <a href="#" class="search"><img src="img/icons/search.png" alt=""></a>
               </div>
               
               <ul class="main-menu">
                   <li><a href="<?= $this->url('home_page') ?>">Home</a></li>
                   <li><a href="#">Woman</a></li>
                   <li><a href="#">Man</a></li>
                   <li><a href="#">LookBook</a></li>
                   <li><a href="#">Blog</a></li>
                   <li><a href="contact.html">Contact</a></li>
               </ul>
           </div>
       </header>

        <!-- <section class="hero-section set-bg" id="banner-home">
            <div class="hero-slider owl-carousel">
                <div class="hs-item">
                    <div class="hs-left"><img src="img/slider-img.png" alt=""></div>
                    <div class="hs-right">
                        <div class="hs-content">
                            <div class="price">from $19.90</div>
                            <h2><span>2018</span> <br>summer collection</h2>
                            <a href="" class="site-btn">Shop NOW!</a>
                        </div>  
                    </div>
                </div>
                <div class="hs-item">
                    <div class="hs-left"><img src="img/slider-img.png" alt=""></div>
                    <div class="hs-right">
                        <div class="hs-content">
                            <div class="price">from $19.90</div>
                            <h2><span>2018</span> <br>summer collection</h2>
                            <a href="" class="site-btn">Shop NOW!</a>
                        </div>  
                    </div>
                </div>
            </div>
        </section> -->
         
    <div class="container">
        <?= $this->content ?>
        <hr>
        <footer>
            <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
        </footer>
    </div>
    <!-- Footer top section --> 
    <section class="footer-top-section home-footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-8 col-sm-12">
                    <div class="footer-widget about-widget">
                        <img src="img/logo.png" class="footer-logo" alt="">
                        <p>Donec vitae purus nunc. Morbi faucibus erat sit amet congue mattis. Nullam fringilla faucibus urna, id dapibus erat iaculis ut. Integer ac sem.</p>
                        <div class="cards">
                            <img src="img/cards/5.png" alt="">
                            <img src="img/cards/4.png" alt="">
                            <img src="img/cards/3.png" alt="">
                            <img src="img/cards/2.png" alt="">
                            <img src="img/cards/1.png" alt="">
                        </div>
                    </div>
                </div>
                <div class="col-lg-2 col-md-4 col-sm-6">
                    <div class="footer-widget">
                        <h6 class="fw-title">usefull Links</h6>
                        <ul>
                            <li><a href="#">Partners</a></li>
                            <li><a href="#">Bloggers</a></li>
                            <li><a href="#">Support</a></li>
                            <li><a href="#">Terms of Use</a></li>
                            <li><a href="#">Press</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-2 col-md-4 col-sm-6">
                    <div class="footer-widget">
                        <h6 class="fw-title">Sitemap</h6>
                        <ul>
                            <li><a href="#">Partners</a></li>
                            <li><a href="#">Bloggers</a></li>
                            <li><a href="#">Support</a></li>
                            <li><a href="#">Terms of Use</a></li>
                            <li><a href="#">Press</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-2 col-md-4 col-sm-6">
                    <div class="footer-widget">
                        <h6 class="fw-title">Shipping & returns</h6>
                        <ul>
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Track Orders</a></li>
                            <li><a href="#">Returns</a></li>
                            <li><a href="#">Jobs</a></li>
                            <li><a href="#">Shipping</a></li>
                            <li><a href="#">Blog</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-2 col-md-4 col-sm-6">
                    <div class="footer-widget">
                        <h6 class="fw-title">Contact</h6>
                        <div class="text-box">
                            <p>Your Company Ltd </p>
                            <p>1481 Creekside Lane  Avila Beach, CA 93424, </p>
                            <p>+53 345 7953 32453</p>
                            <p>office@youremail.com</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Footer top section end --> 

        <!-- Footer section -->
    <footer class="footer-section">
        <div class="container">
            <p class="copyright">
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
        </div>
    </footer>
    <!-- Footer section end -->
       
       <?= $this->inlineScript() ?> 
    </body>
    
</html>
