<?php 
$title = 'Employee application'; 
$this->headTitle($title); 
?>  

<table class="table"> 
   <tr> 
      <th>Employee Name</th> 
      <th>Employee Job</th> 
      <th>Edit/Delete operations</th>
   </tr> 
   
   <tr>  
      <td><?php echo $this->a;?></td> 
      <td><?php echo $this->a;?></td> 
      <td> 
         <a href="<?php echo $this->a ?>">Edit</a> 
         <a href="<?php echo $this->a ?>">Delete</a> 
      </td> 
   </tr> 
 
</table> 